name = "replica-frontend"
main = "frontend/src/index.js"
compatibility_date = "2025-10-15"

[build]
command = "npm install && npm run build"
cwd = "frontend"
upload.format = "service-worker"

[site]
bucket = "frontend/build"
